name: wheather_forecast_app
description: "Weather Forecast App for Sagara MSIB Mobile Test"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: MonaSans
      fonts:
        - asset: assets/fonts/MonaSans-Regular.ttf
        - asset: assets/fonts/MonaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/MonaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/MonaSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/MonaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MonaSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/MonaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/MonaSans-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/MonaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MonaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
